apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: sameersbn/postgresql:9.4-9
      env:
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
      livenessProbe:
        TCPSocket:
          port: 5432
        initialDelaySeconds: 30
        timeoutSeconds: 5
  volumes:
    - name: data
      emptyDir: {}
